project:
  type: book

book:
  title: "Thesis Title"
  author: "Jane Doe"
  date: "January 1, 2013"
  chapters:
    - index.qmd
    - conclusion.qmd
    - references.qmd
  appendices: 
    - appendix.qmd

thesis:    
  department: Statistics
  depttype: Department
  depthead: Head
  doctype: Dissertation
  major: Statistics
  advisor: Jane R. Professor
  coadvisor: John S. Professor
  commencementyear: 2013
  degree: Master of Science
  acknowledgements: I would like to acknowledge...
  abstract: > 
    This is a LaTex template derived from the beavtex template found 
    on the Oregon State University Math Department website.
   
bibliography: references.bib

format:
  html: default
  beav-pdf: 
    keep-tex: true

